language: node_js

matrix:
  include:
  # First test cross-OS packaging using most-significant examples:
  - os: linux
    node_js: v10.0.0
    env:
    - SHOCKPKG_PACKAGES="
        flash-player-11.2.202.644-linux-i386-sa
        flash-player-32.0.0.293-linux-x86_64-sa
        flash-player-32.0.0.293-windows-sa"

  - os: osx
    node_js: v10.0.0
    env:
    - SHOCKPKG_PACKAGES="
        flash-player-11.2.202.644-linux-i386-sa
        flash-player-32.0.0.293-linux-x86_64-sa
        flash-player-32.0.0.293-windows-sa
        flash-player-32.0.0.293-mac-sa"

  - os: windows
    node_js: v10.0.0
    env:
    - SHOCKPKG_PACKAGES="
        flash-player-11.2.202.644-linux-i386-sa
        flash-player-32.0.0.293-linux-x86_64-sa
        flash-player-32.0.0.293-windows-sa"

  - os: linux
    node_js: v12.9.1
    env:
    - SHOCKPKG_PACKAGES="
        flash-player-11.2.202.644-linux-i386-sa
        flash-player-32.0.0.293-linux-x86_64-sa
        flash-player-32.0.0.293-windows-sa"

  - os: osx
    node_js: v12.9.1
    env:
    - SHOCKPKG_PACKAGES="
        flash-player-11.2.202.644-linux-i386-sa
        flash-player-32.0.0.293-linux-x86_64-sa
        flash-player-32.0.0.293-windows-sa
        flash-player-32.0.0.293-mac-sa"

  - os: windows
    node_js: v12.9.1
    env:
    - SHOCKPKG_PACKAGES="
        flash-player-11.2.202.644-linux-i386-sa
        flash-player-32.0.0.293-linux-x86_64-sa
        flash-player-32.0.0.293-windows-sa"

  # Test other Windows versions (including OS specific features):
  - os: windows
    node_js: v12.9.1
    env:    # Only 3.0 32-bit:
    #   flash-player-3.0.8.0-windows-32bit-sa
    # Only 4.0:
    #   flash-player-4.0.7.0-windows-sa
    # Only 5.0 (release, and first debug):
    #   flash-player-5.0.30.0-windows-sa
    #   flash-player-5.0.30.0-windows-sa-debug
    # First 6.0:
    #   flash-player-6.0.21.0-windows-sa
    # Last 6.0:
    #   flash-player-6.0.79.0-windows-sa
    # First 7.0:
    #   flash-player-7.0.14.0-windows-sa
    # Last 7.0:
    #   flash-player-7.0.19.0-windows-sa
    # First 8.0:
    #   flash-player-8.0.22.0-windows-sa
    # Last 8.0:
    #   flash-player-8.0.42.0-windows-sa
    # First 9.0, first code-signed:
    #   flash-player-9.0.15.0-windows-sa-debug
    # First 9.0 release:
    #   flash-player-9.0.115.0-windows-sa
    # Last 9.0 before 10.0:
    #   flash-player-9.0.280.0-windows-sa
    # Last 9.0:
    #   flash-player-9.0.289.0-windows-sa
    # First 10.0:
    #   flash-player-10.0.12.36-windows-sa
    # Last 10.0:
    #   flash-player-10.0.45.2-windows-sa
    # Last 10.3, not code-signed:
    #   flash-player-10.3.183.90-windows-sa
    # First 11.1:
    #   flash-player-11.1.102.55-windows-32bit-sa
    # Latest:
    #   flash-player-32.0.0.293-windows-sa
    #   flash-player-32.0.0.293-windows-sa-debug
    - SHOCKPKG_PACKAGES="
        flash-player-3.0.8.0-windows-32bit-sa
        flash-player-4.0.7.0-windows-sa
        flash-player-5.0.30.0-windows-sa
        flash-player-5.0.30.0-windows-sa-debug
        flash-player-6.0.21.0-windows-sa
        flash-player-6.0.79.0-windows-sa
        flash-player-7.0.14.0-windows-sa
        flash-player-7.0.19.0-windows-sa
        flash-player-8.0.22.0-windows-sa
        flash-player-8.0.42.0-windows-sa
        flash-player-9.0.15.0-windows-sa-debug
        flash-player-9.0.115.0-windows-sa
        flash-player-9.0.280.0-windows-sa
        flash-player-9.0.289.0-windows-sa
        flash-player-10.0.12.36-windows-sa
        flash-player-10.0.45.2-windows-sa
        flash-player-10.3.183.90-windows-sa
        flash-player-11.1.102.55-windows-32bit-sa
        flash-player-32.0.0.293-windows-sa
        flash-player-32.0.0.293-windows-sa-debug"

  # Test other Mac versions (including OS specific features):
  - os: osx
    node_js: v12.9.1
    env:    # First Mac APP bundle, broken icon, DMG:
    #   flash-player-9.0.28.0-mac-sa-debug
    # Early Mac APP bundle, broken icon, ZIP:
    #   flash-player-9.0.45.0-mac-sa-debug
    # First Mac APP, correct icon, ZIP:
    #   flash-player-9.0.115.0-mac-sa
    #   flash-player-9.0.115.0-mac-sa-debug
    # Last 9.0 before 10.0:
    #   flash-player-9.0.280.0-mac-sa
    # Last 9.0:
    #   flash-player-9.0.289.0-mac-sa
    # Last 10.0:
    #   flash-player-10.0.12.36-mac-sa
    # Last before code-signing:
    #   flash-player-10.0.45.2-mac-sa-debug
    # First code-signed:
    #   flash-player-10.1.53.64-mac-sa
    # Revoked cert:
    #   flash-player-10.1.102.64-mac-sa
    # First 10.2, revoked cert:
    #   flash-player-10.2.152.26-mac-sa
    # Last PPC:
    #   flash-player-10.2.153.1-mac-sa
    # Last 10.2, revoked cert, no PPC:
    #   flash-player-10.2.159.1-mac-sa
    # First 10.3, not code-signed:
    #   flash-player-10.3.181.14-mac-sa
    # Last 10.3, code-signed:
    #   flash-player-10.3.183.90-mac-sa
    # Only 11.0, first i386/x86_64, revoked cert:
    #   flash-player-11.0.1.152-mac-sa
    # First 11.1:
    #   flash-player-11.1.102.55-mac-sa
    # Last signature V1:
    #   flash-player-15.0.0.152-mac-sa-debug
    # First signature V2:
    #   flash-player-15.0.0.189-mac-sa-debug
    # Latest:
    #   flash-player-32.0.0.293-mac-sa
    #   flash-player-32.0.0.293-mac-sa-debug
    - SHOCKPKG_PACKAGES="
        flash-player-9.0.28.0-mac-sa-debug
        flash-player-9.0.45.0-mac-sa-debug
        flash-player-9.0.115.0-mac-sa
        flash-player-9.0.115.0-mac-sa-debug
        flash-player-9.0.280.0-mac-sa
        flash-player-9.0.289.0-mac-sa
        flash-player-10.0.12.36-mac-sa
        flash-player-10.0.45.2-mac-sa-debug
        flash-player-10.1.53.64-mac-sa
        flash-player-10.1.102.64-mac-sa
        flash-player-10.2.152.26-mac-sa
        flash-player-10.2.153.1-mac-sa
        flash-player-10.2.159.1-mac-sa
        flash-player-10.3.181.14-mac-sa
        flash-player-10.3.183.90-mac-sa
        flash-player-11.0.1.152-mac-sa
        flash-player-11.1.102.55-mac-sa
        flash-player-15.0.0.152-mac-sa-debug
        flash-player-15.0.0.189-mac-sa-debug
        flash-player-32.0.0.293-mac-sa
        flash-player-32.0.0.293-mac-sa-debug"

  # Test other Linux i386 versions:
  - os: linux
    node_js: v12.9.1
    env:    # Only 6.0, first version (ZLIB):
    #   flash-player-6.0.79.0-linux-sa
    # First 9.0:
    #   flash-player-9.0.115.0-linux-sa
    # First debug:
    #   flash-player-9.0.115.0-linux-sa-debug
    # Last 9.0 before 10.0:
    #   flash-player-9.0.280.0-linux-sa
    # Last 9.0:
    #   flash-player-9.0.289.0-linux-sa
    # First 10.0:
    #   flash-player-10.0.12.36-linux-sa
    # Last 10.3:
    #   flash-player-10.3.183.90-linux-sa
    # First 11.0:
    #   flash-player-11.0.1.152-linux-i386-sa
    #   flash-player-11.0.1.152-linux-i386-sa-debug
    # First 11.1 (LZMA):
    #   flash-player-11.1.102.55-linux-i386-sa
    # Last 11.2, last i386, before long release break:
    #   flash-player-11.2.202.644-linux-i386-sa
    #   flash-player-11.2.202.644-linux-i386-sa-debug
    - SHOCKPKG_PACKAGES="
        flash-player-6.0.79.0-linux-sa
        flash-player-9.0.115.0-linux-sa
        flash-player-9.0.115.0-linux-sa-debug
        flash-player-9.0.280.0-linux-sa
        flash-player-9.0.289.0-linux-sa
        flash-player-10.0.12.36-linux-sa
        flash-player-10.3.183.90-linux-sa
        flash-player-11.0.1.152-linux-i386-sa
        flash-player-11.0.1.152-linux-i386-sa-debug
        flash-player-11.1.102.55-linux-i386-sa
        flash-player-11.2.202.644-linux-i386-sa
        flash-player-11.2.202.644-linux-i386-sa-debug"

  # Test every Linux x86_64 version (ensures ASM patch works on all versions):
  - os: linux
    node_js: v12.9.1
    env:
    - SHOCKPKG_PACKAGES="
        flash-player-32.0.0.101-linux-x86_64-sa
        flash-player-32.0.0.101-linux-x86_64-sa-debug
        flash-player-32.0.0.114-linux-x86_64-sa
        flash-player-32.0.0.114-linux-x86_64-sa-debug
        flash-player-32.0.0.142-linux-x86_64-sa
        flash-player-32.0.0.142-linux-x86_64-sa-debug
        flash-player-32.0.0.156-linux-x86_64-sa
        flash-player-32.0.0.156-linux-x86_64-sa-debug
        flash-player-32.0.0.171-linux-x86_64-sa
        flash-player-32.0.0.171-linux-x86_64-sa-debug
        flash-player-32.0.0.192-linux-x86_64-sa
        flash-player-32.0.0.192-linux-x86_64-sa-debug
        flash-player-32.0.0.207-linux-x86_64-sa
        flash-player-32.0.0.207-linux-x86_64-sa-debug
        flash-player-32.0.0.223-linux-x86_64-sa
        flash-player-32.0.0.223-linux-x86_64-sa-debug
        flash-player-32.0.0.238-linux-x86_64-sa
        flash-player-32.0.0.238-linux-x86_64-sa-debug
        flash-player-32.0.0.255-linux-x86_64-sa
        flash-player-32.0.0.255-linux-x86_64-sa-debug
        flash-player-32.0.0.270-linux-x86_64-sa
        flash-player-32.0.0.270-linux-x86_64-sa-debug
        flash-player-32.0.0.293-linux-x86_64-sa
        flash-player-32.0.0.293-linux-x86_64-sa-debug"

  - os: linux
    node_js: v12.9.1
    env:
    - SHOCKPKG_PACKAGES="
        flash-player-31.0.0.108-linux-x86_64-sa
        flash-player-31.0.0.108-linux-x86_64-sa-debug
        flash-player-31.0.0.122-linux-x86_64-sa
        flash-player-31.0.0.122-linux-x86_64-sa-debug
        flash-player-31.0.0.148-linux-x86_64-sa
        flash-player-31.0.0.148-linux-x86_64-sa-debug
        flash-player-31.0.0.153-linux-x86_64-sa
        flash-player-31.0.0.153-linux-x86_64-sa-debug"

  - os: linux
    node_js: v12.9.1
    env:
    - SHOCKPKG_PACKAGES="
        flash-player-30.0.0.113-linux-x86_64-sa
        flash-player-30.0.0.113-linux-x86_64-sa-debug
        flash-player-30.0.0.134-linux-x86_64-sa
        flash-player-30.0.0.134-linux-x86_64-sa-debug
        flash-player-30.0.0.154-linux-x86_64-sa
        flash-player-30.0.0.154-linux-x86_64-sa-debug"

  - os: linux
    node_js: v12.9.1
    env:
    - SHOCKPKG_PACKAGES="
        flash-player-29.0.0.113-linux-x86_64-sa
        flash-player-29.0.0.113-linux-x86_64-sa-debug
        flash-player-29.0.0.140-linux-x86_64-sa
        flash-player-29.0.0.140-linux-x86_64-sa-debug
        flash-player-29.0.0.171-linux-x86_64-sa
        flash-player-29.0.0.171-linux-x86_64-sa-debug"

  - os: linux
    node_js: v12.9.1
    env:
    - SHOCKPKG_PACKAGES="
        flash-player-28.0.0.126-linux-x86_64-sa
        flash-player-28.0.0.126-linux-x86_64-sa-debug
        flash-player-28.0.0.137-linux-x86_64-sa
        flash-player-28.0.0.137-linux-x86_64-sa-debug
        flash-player-28.0.0.161-linux-x86_64-sa
        flash-player-28.0.0.161-linux-x86_64-sa-debug"

  - os: linux
    node_js: v12.9.1
    env:
    - SHOCKPKG_PACKAGES="
        flash-player-27.0.0.130-linux-x86_64-sa
        flash-player-27.0.0.130-linux-x86_64-sa-debug
        flash-player-27.0.0.159-linux-x86_64-sa
        flash-player-27.0.0.159-linux-x86_64-sa-debug
        flash-player-27.0.0.170-linux-x86_64-sa
        flash-player-27.0.0.170-linux-x86_64-sa-debug
        flash-player-27.0.0.183-linux-x86_64-sa
        flash-player-27.0.0.183-linux-x86_64-sa-debug
        flash-player-27.0.0.187-linux-x86_64-sa
        flash-player-27.0.0.187-linux-x86_64-sa-debug"

  - os: linux
    node_js: v12.9.1
    env:
    - SHOCKPKG_PACKAGES="
        flash-player-26.0.0.126-linux-x86_64-sa
        flash-player-26.0.0.126-linux-x86_64-sa-debug
        flash-player-26.0.0.131-linux-x86_64-sa
        flash-player-26.0.0.131-linux-x86_64-sa-debug
        flash-player-26.0.0.137-linux-x86_64-sa
        flash-player-26.0.0.137-linux-x86_64-sa-debug
        flash-player-26.0.0.151-linux-x86_64-sa
        flash-player-26.0.0.151-linux-x86_64-sa-debug"

  - os: linux
    node_js: v12.9.1
    env:
    - SHOCKPKG_PACKAGES="
        flash-player-25.0.0.127-linux-x86_64-sa
        flash-player-25.0.0.127-linux-x86_64-sa-debug
        flash-player-25.0.0.148-linux-x86_64-sa
        flash-player-25.0.0.148-linux-x86_64-sa-debug
        flash-player-25.0.0.171-linux-x86_64-sa
        flash-player-25.0.0.171-linux-x86_64-sa-debug"

  - os: linux
    node_js: v12.9.1
    env:
    - SHOCKPKG_PACKAGES="
        flash-player-24.0.0.186-linux-x86_64-sa
        flash-player-24.0.0.186-linux-x86_64-sa-debug
        flash-player-24.0.0.194-linux-x86_64-sa
        flash-player-24.0.0.194-linux-x86_64-sa-debug
        flash-player-24.0.0.221-linux-x86_64-sa
        flash-player-24.0.0.221-linux-x86_64-sa-debug

script:
- env
- npm run shockpkg update
- npm run shockpkg install $SHOCKPKG_PACKAGES
- npm run clean
- npm run lint
- npm run build
- npm run test
