language: node_js

matrix:
  include:
  - os: linux
    node_js: v10.0.0
    env:
    - SHOCKPKG_INSTALL=shockpkg-install-ci

  - os: osx
    osx_image: xcode10.2
    node_js: v10.0.0
    env:
    - SHOCKPKG_INSTALL=shockpkg-install-ci

  - os: windows
    node_js: v10.0.0
    env:
    - SHOCKPKG_INSTALL=shockpkg-install-full-ci

  - os: linux
    node_js: v10.16.2
    env:
    - SHOCKPKG_INSTALL=shockpkg-install-ci

  - os: osx
    osx_image: xcode10.2
    node_js: v10.16.2
    env:
    - SHOCKPKG_INSTALL=shockpkg-install-ci

  - os: windows
    node_js: v10.16.2
    env:
    - SHOCKPKG_INSTALL=shockpkg-install-full-ci

  - os: linux
    node_js: v12.8.0
    env:
    - SHOCKPKG_INSTALL=shockpkg-install-ci

  - os: osx
    osx_image: xcode10.2
    node_js: v12.8.0
    env:
    - SHOCKPKG_INSTALL=shockpkg-install-ci

  - os: windows
    node_js: v12.8.0
    env:
    - SHOCKPKG_INSTALL=shockpkg-install-full-ci

script:
- npm run "${SHOCKPKG_INSTALL}"
- npm run clean
- npm run lint
- npm run build
- npm run test
