C7 44 24 08 -- -- -- --         mov     DWORD PTR [esp+0x8], ...
C7 44 24 04 -- -- -- --         mov     DWORD PTR [esp+0x4], ...
89 -- 24                        mov     DWORD PTR [esp], ...
E8 -- -- -- --                  call    ...
