8D 83 -- -- -- --               lea     eax, [ebx+...]
89 44 24 04                     mov     DWORD PTR [esp+0x4], eax
C7 44 24 08 -- -- -- --         mov     DWORD PTR [esp+0x8], ...
89 34 24                        mov     DWORD PTR [esp], esi
E8 -- -- -- --                  call    ...
