E8 -- -- -- --                  call    _gtk_widget_show
5F                              pop     edi
58                              pop     eax
FF 35 -- -- -- --               push    DWORD PTR ds:...
-- -- --                        ...
-- -- --                        ...
E8 -- -- -- --                  call    _gdk_window_set_title
