E8 -- -- -- --                  call    _gtk_widget_show
A1 -- -- -- --                  mov     eax, DWORD PTR ds:....
89 44 24 04                     mov     DWORD PTR [esp+0x4], eax
-- -- -- -- -- --               ...
-- -- --                        ...
89 -- 24                        mov     DWORD PTR [esp], eax
E8 -- -- -- --                  call    _gtk_window_set_title
