0F 84 -- -- -- --               je      ...
8D 9D E0 EF FF FF               lea     ebx, [ebp-0x1020]
C7 44 24 04 -- -- -- --         mov     DWORD PTR [esp+0x4], ...
89 1C 24                        mov     DWORD PTR [esp], ebx
E8 -- -- -- --                  call    ...
