0F 84 -- -- -- --               je      ...
8D 5D E8                        lea     ebx, [ebp-0x18]
BE -- -- -- --                  mov     esi, ...
89 74 24 04                     mov     DWORD PTR [esp+0x4], esi
89 1C 24                        mov     DWORD PTR [esp], ebx
E8 -- -- -- --                  call    ...
