name: 'linux-9.0.100'

on: push

jobs:
  build:
    runs-on: 'ubuntu-20.04'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '16.1.0'

    - run: npm install
    - run: npm run clean
    - run: npm run shockpkg -- update --summary
    - run: npm run shockpkg -- install flash-player-9.0.115.0-linux-sa flash-player-9.0.115.0-linux-sa-debug flash-player-9.0.124.0-linux-sa flash-player-9.0.124.0-linux-sa-debug flash-player-9.0.151.0-linux-sa flash-player-9.0.151.0-linux-sa-debug flash-player-9.0.152.0-linux-sa flash-player-9.0.152.0-linux-sa-debug flash-player-9.0.159.0-linux-sa flash-player-9.0.159.0-linux-sa-debug

    - run: npm run build
    - run: npm run test
