name: 'linux-10.0'

on: push

jobs:
  build:
    runs-on: 'ubuntu-20.04'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '15.13.0'

    - run: npm install
    - run: npm run clean
    - run: npm run shockpkg -- update --summary
    - run: npm run shockpkg -- install flash-player-10.0.12.36-linux-sa flash-player-10.0.12.36-linux-sa-debug flash-player-10.0.15.3-linux-sa flash-player-10.0.15.3-linux-sa-debug flash-player-10.0.22.87-linux-sa flash-player-10.0.22.87-linux-sa-debug flash-player-10.0.32.18-linux-sa flash-player-10.0.32.18-linux-sa-debug flash-player-10.0.42.34-linux-sa flash-player-10.0.42.34-linux-sa-debug flash-player-10.0.45.2-linux-sa-debug

    - run: npm run build
    - run: npm run test
