name: 'linux-11.2.202.600'

on: push

jobs:
  build:
    runs-on: 'ubuntu-20.04'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '15.5.0'

    - run: npm install
    - run: npm run clean
    - run: npm run shockpkg -- update --summary
    - run: npm run shockpkg -- install flash-player-11.2.202.616-linux-i386-sa flash-player-11.2.202.616-linux-i386-sa-debug flash-player-11.2.202.621-linux-i386-sa flash-player-11.2.202.621-linux-i386-sa-debug flash-player-11.2.202.626-linux-i386-sa flash-player-11.2.202.626-linux-i386-sa-debug flash-player-11.2.202.632-linux-i386-sa flash-player-11.2.202.632-linux-i386-sa-debug flash-player-11.2.202.635-linux-i386-sa flash-player-11.2.202.635-linux-i386-sa-debug flash-player-11.2.202.637-linux-i386-sa flash-player-11.2.202.637-linux-i386-sa-debug flash-player-11.2.202.643-linux-i386-sa flash-player-11.2.202.643-linux-i386-sa-debug flash-player-11.2.202.644-linux-i386-sa flash-player-11.2.202.644-linux-i386-sa-debug

    - run: npm run build
    - run: npm run test
