name: 'linux-10.2'

on: push

jobs:
  build:
    runs-on: 'ubuntu-20.04'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '15.13.0'

    - run: npm install
    - run: npm run clean
    - run: npm run shockpkg -- update --summary
    - run: npm run shockpkg -- install flash-player-10.2.152.26-linux-sa flash-player-10.2.152.26-linux-sa-debug flash-player-10.2.153.1-linux-sa flash-player-10.2.153.1-linux-sa-debug flash-player-10.2.159.1-linux-sa flash-player-10.2.159.1-linux-sa-debug

    - run: npm run build
    - run: npm run test
