name: 'linux-27'

on: push

jobs:
  build:
    runs-on: 'ubuntu-20.04'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '16.5.0'

    - run: npm install
    - run: npm run clean
    - run: npm run shockpkg -- update --summary
    - run: npm run shockpkg -- install flash-player-27.0.0.130-linux-x86_64-sa flash-player-27.0.0.130-linux-x86_64-sa-debug flash-player-27.0.0.159-linux-x86_64-sa flash-player-27.0.0.159-linux-x86_64-sa-debug flash-player-27.0.0.170-linux-x86_64-sa flash-player-27.0.0.170-linux-x86_64-sa-debug flash-player-27.0.0.183-linux-x86_64-sa flash-player-27.0.0.183-linux-x86_64-sa-debug flash-player-27.0.0.187-linux-x86_64-sa flash-player-27.0.0.187-linux-x86_64-sa-debug

    - run: npm run build
    - run: npm run test
