name: 'linux-32.0.0.400'

on: push

jobs:
  build:
    runs-on: 'ubuntu-20.04'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '15.5.0'

    - run: npm install
    - run: npm run clean
    - run: npm run shockpkg -- update --summary
    - run: npm run shockpkg -- install flash-player-32.0.0.403-linux-x86_64-sa flash-player-32.0.0.403-linux-x86_64-sa-debug flash-player-32.0.0.414-linux-x86_64-sa flash-player-32.0.0.414-linux-x86_64-sa-debug flash-player-32.0.0.433-linux-x86_64-sa flash-player-32.0.0.433-linux-x86_64-sa-debug flash-player-32.0.0.445-linux-x86_64-sa flash-player-32.0.0.445-linux-x86_64-sa-debug flash-player-32.0.0.453-linux-x86_64-sa flash-player-32.0.0.453-linux-x86_64-sa-debug flash-player-32.0.0.465-linux-x86_64-sa flash-player-32.0.0.465-linux-x86_64-sa-debug
    - run: npm run lint
    - run: npm run build
    - run: npm run test
