name: 'linux-10.3.181.14-10.3.183.18'

on: push

jobs:
  build:
    runs-on: 'ubuntu-20.04'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '16.5.0'

    - run: npm install
    - run: npm run clean
    - run: npm run shockpkg -- update --summary
    - run: npm run shockpkg -- install flash-player-10.3.181.14-linux-sa flash-player-10.3.181.14-linux-sa-debug flash-player-10.3.181.22-linux-sa flash-player-10.3.181.22-linux-sa-debug flash-player-10.3.181.26-linux-sa flash-player-10.3.181.26-linux-sa-debug flash-player-10.3.181.34-linux-sa flash-player-10.3.181.34-linux-sa-debug flash-player-10.3.183.5-linux-sa flash-player-10.3.183.5-linux-sa-debug flash-player-10.3.183.7-linux-sa flash-player-10.3.183.7-linux-sa-debug flash-player-10.3.183.10-linux-sa flash-player-10.3.183.10-linux-sa-debug flash-player-10.3.183.11-linux-sa flash-player-10.3.183.11-linux-sa-debug flash-player-10.3.183.15-linux-sa flash-player-10.3.183.15-linux-sa-debug flash-player-10.3.183.16-linux-sa flash-player-10.3.183.16-linux-sa-debug flash-player-10.3.183.18-linux-sa flash-player-10.3.183.18-linux-sa-debug

    - run: npm run build
    - run: npm run test
