name: 'linux-32.0.0.300'

on: push

jobs:
  build:
    runs-on: 'ubuntu-20.04'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '15.13.0'

    - run: npm install
    - run: npm run clean
    - run: npm run shockpkg -- update --summary
    - run: npm run shockpkg -- install flash-player-32.0.0.303-linux-x86_64-sa flash-player-32.0.0.303-linux-x86_64-sa-debug flash-player-32.0.0.314-linux-x86_64-sa flash-player-32.0.0.314-linux-x86_64-sa-debug flash-player-32.0.0.321-linux-x86_64-sa flash-player-32.0.0.321-linux-x86_64-sa-debug flash-player-32.0.0.330-linux-x86_64-sa flash-player-32.0.0.330-linux-x86_64-sa-debug flash-player-32.0.0.344-linux-x86_64-sa flash-player-32.0.0.344-linux-x86_64-sa-debug flash-player-32.0.0.363-linux-x86_64-sa flash-player-32.0.0.363-linux-x86_64-sa-debug flash-player-32.0.0.371-linux-x86_64-sa flash-player-32.0.0.371-linux-x86_64-sa-debug flash-player-32.0.0.387-linux-x86_64-sa flash-player-32.0.0.387-linux-x86_64-sa-debug

    - run: npm run build
    - run: npm run test
