name: 'linux-11.2.202.200'

on: push

jobs:
  build:
    runs-on: 'ubuntu-20.04'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '15.13.0'

    - run: npm install
    - run: npm run clean
    - run: npm run shockpkg -- update --summary
    - run: npm run shockpkg -- install flash-player-11.2.202.228-linux-i386-sa flash-player-11.2.202.228-linux-i386-sa-debug flash-player-11.2.202.233-linux-i386-sa flash-player-11.2.202.233-linux-i386-sa-debug flash-player-11.2.202.235-linux-i386-sa flash-player-11.2.202.235-linux-i386-sa-debug flash-player-11.2.202.238-linux-i386-sa flash-player-11.2.202.238-linux-i386-sa-debug flash-player-11.2.202.243-linux-i386-sa flash-player-11.2.202.243-linux-i386-sa-debug flash-player-11.2.202.251-linux-i386-sa flash-player-11.2.202.251-linux-i386-sa-debug flash-player-11.2.202.258-linux-i386-sa flash-player-11.2.202.258-linux-i386-sa-debug flash-player-11.2.202.261-linux-i386-sa flash-player-11.2.202.261-linux-i386-sa-debug flash-player-11.2.202.262-linux-i386-sa flash-player-11.2.202.262-linux-i386-sa-debug flash-player-11.2.202.270-linux-i386-sa flash-player-11.2.202.270-linux-i386-sa-debug flash-player-11.2.202.273-linux-i386-sa flash-player-11.2.202.273-linux-i386-sa-debug flash-player-11.2.202.275-linux-i386-sa flash-player-11.2.202.275-linux-i386-sa-debug flash-player-11.2.202.280-linux-i386-sa flash-player-11.2.202.280-linux-i386-sa-debug flash-player-11.2.202.285-linux-i386-sa flash-player-11.2.202.285-linux-i386-sa-debug flash-player-11.2.202.291-linux-i386-sa flash-player-11.2.202.291-linux-i386-sa-debug flash-player-11.2.202.297-linux-i386-sa flash-player-11.2.202.297-linux-i386-sa-debug

    - run: npm run build
    - run: npm run test
