name: 'linux-10.3.183.20-10.3.183.90'

on: push

jobs:
  build:
    runs-on: 'ubuntu-20.04'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '15.13.0'

    - run: npm install
    - run: npm run clean
    - run: npm run shockpkg -- update --summary
    - run: npm run shockpkg -- install flash-player-10.3.183.20-linux-sa flash-player-10.3.183.20-linux-sa-debug flash-player-10.3.183.23-linux-sa flash-player-10.3.183.23-linux-sa-debug flash-player-10.3.183.29-linux-sa flash-player-10.3.183.29-linux-sa-debug flash-player-10.3.183.43-linux-sa flash-player-10.3.183.43-linux-sa-debug flash-player-10.3.183.48-linux-sa-debug flash-player-10.3.183.50-linux-sa flash-player-10.3.183.50-linux-sa-debug flash-player-10.3.183.51-linux-sa flash-player-10.3.183.51-linux-sa-debug flash-player-10.3.183.61-linux-sa flash-player-10.3.183.61-linux-sa-debug flash-player-10.3.183.67-linux-sa flash-player-10.3.183.67-linux-sa-debug flash-player-10.3.183.68-linux-sa flash-player-10.3.183.68-linux-sa-debug flash-player-10.3.183.75-linux-sa flash-player-10.3.183.75-linux-sa-debug flash-player-10.3.183.86-linux-sa flash-player-10.3.183.86-linux-sa-debug flash-player-10.3.183.90-linux-sa flash-player-10.3.183.90-linux-sa-debug

    - run: npm run build
    - run: npm run test
