name: 'linux-31'

on: push

jobs:
  build:
    runs-on: 'ubuntu-20.04'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '15.13.0'

    - run: npm install
    - run: npm run clean
    - run: npm run shockpkg -- update --summary
    - run: npm run shockpkg -- install flash-player-31.0.0.108-linux-x86_64-sa flash-player-31.0.0.108-linux-x86_64-sa-debug flash-player-31.0.0.122-linux-x86_64-sa flash-player-31.0.0.122-linux-x86_64-sa-debug flash-player-31.0.0.148-linux-x86_64-sa flash-player-31.0.0.148-linux-x86_64-sa-debug flash-player-31.0.0.153-linux-x86_64-sa flash-player-31.0.0.153-linux-x86_64-sa-debug

    - run: npm run build
    - run: npm run test
