name: main

on: push

jobs:
  build:
    strategy:
      matrix:
        config:
          - node-version: '14.15.0' # LTS
            NO_FORMATTED: 1
            NO_LINT: 1
            PKG: ''

          - node-version: '16.13.0' # LTS
            NO_FORMATTED: 1
            NO_LINT: 1
            PKG: ''

          - node-version: '16.16.0' # LTS (current)
            PKG: ''

          - node-version: '18.6.0' # Latest
            PKG: ''

          # Notable Windows versions
          - node-version: '16.16.0' # LTS (current)
            NO_FORMATTED: 1
            NO_LINT: 1
            PKG:
              # Version 35.0.0.204:
              - flash-player-35.0.0.204-windows-i386-sa-2022-07-04
              - flash-player-35.0.0.204-windows-x86_64-sa-2022-08-13
              - flash-player-35.0.0.204-windows-x86_64-sa-debug-2022-08-13
              # Version 35.0.0.1:
              - flash-player-35.0.0.1-windows-i386-sa-2022-03-08
              - flash-player-35.0.0.1-windows-x86_64-sa-2022-03-16
              - flash-player-35.0.0.1-windows-x86_64-sa-debug-2022-03-16
              # Latest pre-EOL:
              - flash-player-32.0.0.465-windows-sa
              - flash-player-32.0.0.465-windows-sa-debug
              # Latest 32 also available for x86_64:
              - flash-player-32.0.0.414-windows-sa
              - flash-player-32.0.0.414-windows-sa-debug
              - flash-player-32.0.0.414-windows-x86_64-sa-2020-10-02
              - flash-player-32.0.0.414-windows-x86_64-sa-debug-2020-10-02
              # First OOD:
              - flash-player-30.0.0.113-windows-sa
              - flash-player-30.0.0.113-windows-sa-debug
              - flash-player-30.0.0.134-windows-x86_64-sa-2018-09-19
              - flash-player-30.0.0.134-windows-x86_64-sa-debug-2018-09-19
              # First version also available for x86_64:
              - flash-player-26.0.0.137-windows-sa
              - flash-player-26.0.0.137-windows-sa-debug
              - flash-player-26.0.0.137-windows-x86_64-sa-2017-12-05
              - flash-player-26.0.0.137-windows-x86_64-sa-debug-2017-12-05
              # First 11.1:
              - flash-player-11.1.102.55-windows-32bit-sa
              # Last 10.3, not code-signed:
              - flash-player-10.3.183.90-windows-sa
              # Last 10.0:
              - flash-player-10.0.45.2-windows-sa
              # First 10.0:
              - flash-player-10.0.12.36-windows-sa
              # Last 9.0:
              - flash-player-9.0.289.0-windows-sa
              # Last 9.0 before 10.0:
              - flash-player-9.0.280.0-windows-sa
              # First 9.0 release:
              - flash-player-9.0.115.0-windows-sa
              # First 9.0, first code-signed:
              - flash-player-9.0.15.0-windows-sa-debug
              # Last 8.0:
              - flash-player-8.0.42.0-windows-sa
              # First 8.0:
              - flash-player-8.0.22.0-windows-sa
              # Last 7.0:
              - flash-player-7.0.19.0-windows-sa
              # First 7.0:
              - flash-player-7.0.14.0-windows-sa
              # Last 6.0:
              - flash-player-6.0.79.0-windows-sa
              # First 6.0:
              - flash-player-6.0.4.0-windows-sa
              - flash-player-6.0.21.0-windows-sa
              # Only 5.0 (release, and first debug):
              - flash-player-5.0.30.0-windows-sa
              - flash-player-5.0.30.0-windows-sa-debug
              # Only 4.0:
              - flash-player-4.0.4.0-windows-sa
              - flash-player-4.0.7.0-windows-sa
              # Only 3.0 32-bit:
              - flash-player-3.0.8.0-windows-32bit-sa

          # Notable Mac versions
          - node-version: '16.16.0' # LTS (current)
            NO_FORMATTED: 1
            NO_LINT: 1
            PKG:
              # Version 35.0.0.204:
              - flash-player-35.0.0.204-mac-x86_64-sa-2022-07-04
              - flash-player-35.0.0.204-mac-x86_64-sa-debug-2022-07-04
              # Version 35.0.0.1:
              - flash-player-35.0.0.1-mac-x86_64-sa-2022-03-08
              - flash-player-35.0.0.1-mac-x86_64-sa-debug-2022-03-08
              # Latest pre-EOL:
              - flash-player-32.0.0.465-mac-sa-zip
              - flash-player-32.0.0.465-mac-sa-debug-zip
              # First x86_64:
              - flash-player-32.0.0.255-mac-sa-zip
              # Last i386+x86_64:
              - flash-player-32.0.0.238-mac-sa-zip
              # First signature V2:
              - flash-player-15.0.0.189-mac-sa-debug-zip
              # Last signature V1:
              - flash-player-15.0.0.152-mac-sa-debug-zip
              # First 11.1:
              - flash-player-11.1.102.55-mac-sa
              # First i386+x86_64, only 11.0, revoked cert:
              - flash-player-11.0.1.152-mac-sa
              # Last i386, last 10.3, code-signed:
              - flash-player-10.3.183.90-mac-sa
              # First 10.3, not code-signed:
              - flash-player-10.3.181.14-mac-sa
              # Last 10.2, revoked cert, no PPC:
              - flash-player-10.2.159.1-mac-sa
              # First i386, first 10.2, revoked cert:
              - flash-player-10.2.152.26-mac-sa
              # Last ppc+i386, revoked cert:
              - flash-player-10.1.102.64-mac-sa
              # First code-signed:
              - flash-player-10.1.53.64-mac-sa
              # Last before code-signing:
              - flash-player-10.0.45.2-mac-sa-debug
              # Last 10.0:
              - flash-player-10.0.12.36-mac-sa
              # Last 9.0:
              - flash-player-9.0.289.0-mac-sa
              # Last 9.0 before 10.0:
              - flash-player-9.0.280.0-mac-sa
              # First Mac APP, correct icon:
              - flash-player-9.0.115.0-mac-sa
              - flash-player-9.0.115.0-mac-sa-debug
              # Early Mac APP bundle, broken icon, ZIP:
              - flash-player-9.0.45.0-mac-sa-debug
              # First Mac APP bundle, broken icon, DMG:
              - flash-player-9.0.28.0-mac-sa-debug-zip

          # Notable Linux x86_64 versions
          - node-version: '16.16.0' # LTS (current)
            NO_FORMATTED: 1
            NO_LINT: 1
            PKG:
              # Last version:
              - flash-player-32.0.0.465-linux-x86_64-sa
              - flash-player-32.0.0.465-linux-x86_64-sa-debug
              # Variant (offset, menu) change over:
              - flash-player-32.0.0.293-linux-x86_64-sa
              - flash-player-32.0.0.293-linux-x86_64-sa-debug
              - flash-player-32.0.0.270-linux-x86_64-sa
              - flash-player-32.0.0.270-linux-x86_64-sa-debug
              # Variant (offset) change change over:
              - flash-player-25.0.0.127-linux-x86_64-sa
              - flash-player-25.0.0.127-linux-x86_64-sa-debug
              - flash-player-25.0.0.148-linux-x86_64-sa
              - flash-player-25.0.0.148-linux-x86_64-sa-debug
              # First version:
              - flash-player-24.0.0.186-linux-x86_64-sa
              - flash-player-24.0.0.186-linux-x86_64-sa-debug

          # Notable Linux i386 versions
          - node-version: '16.16.0' # LTS (current)
            NO_FORMATTED: 1
            NO_LINT: 1
            PKG:
              # Version 11.2, last version:
              - flash-player-11.2.202.644-linux-i386-sa
              - flash-player-11.2.202.644-linux-i386-sa-debug
              # Variant (path, title, menu) change over:
              - flash-player-11.2.202.228-linux-i386-sa
              - flash-player-11.2.202.228-linux-i386-sa-debug
              - flash-player-11.1.102.63-linux-i386-sa
              - flash-player-11.1.102.63-linux-i386-sa-debug
              # Variant (path) change over:
              - flash-player-11.0.1.152-linux-i386-sa
              - flash-player-11.0.1.152-linux-i386-sa-debug
              - flash-player-10.3.183.90-linux-sa
              - flash-player-10.3.183.90-linux-sa-debug
              # Variant (path) change over:
              - flash-player-10.0.12.36-linux-sa
              - flash-player-10.0.12.36-linux-sa-debug
              - flash-player-9.0.289.0-linux-sa
              - flash-player-9.0.289.0-linux-sa-debug
              # Variant (path, title) change over:
              - flash-player-10.1.53.64-linux-sa
              - flash-player-10.1.53.64-linux-sa-debug
              - flash-player-10.0.42.34-linux-sa-debug
              - flash-player-10.0.45.2-linux-sa-debug
              # Variant (path, title, menu) change over, first versions:
              - flash-player-9.0.115.0-linux-sa
              - flash-player-9.0.115.0-linux-sa-debug
              - flash-player-6.0.79.0-linux-sa

    runs-on: 'ubuntu-20.04'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.config.node-version }}

      - name: Dependencies
        run: npm ci

      - name: shockpkg Update
        run: npm run shockpkg -- update --summary

      - name: shockpkg Install
        run: npm run shockpkg -- install ${{ join(matrix.config.PKG, ' ') }}
        if: matrix.config.PKG != ''

      - name: Build
        run: npm run build

      - name: Test CJS
        run: npm run test:cjs

      - name: Test ESM
        run: npm run test:esm

      - name: Lint
        run: npm run lint
        if: matrix.config.NO_LINT != 1

      - name: Formatted
        run: npm run formatted
        if: matrix.config.NO_FORMATTED != 1

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
          registry-url: https://registry.npmjs.org/

      - name: Dependencies
        run: npm ci

      - name: Publish
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
